# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arnau Lagarda Tous
title: Bioinformatician | Senior Project Manager
email: arnau.mobil@gmail.com
phone: +34 697145527 

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Alagarda
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Arnau and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Cats</mark> and <mark>Eating Pizza</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anaxomics Biotech S.L.
        link: https://www.anaxomics.com/
        # link_text: boringcompany.com
        sub_title: Project Manager
        caption: March 2020 - Present
        quote: >
          Artificial Intelligence & Systems Biology solutions: not just the evidence, also the reason behind it
        description: | # this will include new lines to allow paragraphs
          Anaxomics is an SME providing services in biomedical data analysis through the use of cutting-edge artificial intelligence for the combination of systems biology and machine learning methods. 
          
          My role in Anaxomics is varied. In one hand, I am responsible for compiling, preparing and performing high-throughput data analyses (e.g. RNA-seq, microarray) through state of the art methodologies -differential expression analyses, enrichments, machine learning classifiers- geared towards stakeholders needs. In addition, I am also responsible for organizing the team for the performance of diverse data analyses when necessary, taking care of the communication with the client, and providing written results reports and visualizations to our clients to support our findings.
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universitat Autònoma de Barcelona
        caption: 2019 - 2020
        sub_title: MSc in Bioinformatics
        quote: >
          The MSc in Bioinformatics at Universitat Autonoma de Barcelona equips students with the interdisciplinary skills needed to unlock the potential of biological data through advanced computational analysis, preparing them for impactful careers in research, industry, and beyond.
        description: | # this will include new lines to allow paragraphs
          During my Masters degree in Bioinformatics, I discovered the wonderful sensation of mixed relief and warmth from having a complex problem or tedious task being solved through coding. As a one year program, the intensity and the tight work schedule created an environment where my colleagues and I would spend hour after hour working together to improve our programming skills as well as learning new computational biology techniques frantically. 
          The program offered specialization on Genomics, Proteomics or High Performance Computing, with the latter being my choice. There, we were introduced to concepts that none of us coming from a biological sciences background would have heard of during our bachelors such as code optimization, cloud computing, artificial neural networks and machine learning.
        
      - layout: left
        title: Universitat Autònoma de Barcelona
        caption: 2015 - 2019
        sub_title: BSc in Microbiology
        quote: >
          Through a rigorous curriculum emphasizing hands-on laboratory experience and a deep understanding of microorganisms, their interactions with the environment and their molecular biology, the BSc in Microbiology at Universitat Autonoma de Barcelona prepares students for careers at the forefront of understanding and combatting infectious disease, biotechnology, and environmental sustainability.
        description: | # this will include new lines to allow paragraphs
          While pursuing a BSc in Microbiology at Universitat Autonoma de Barcelona, I gained a deep understanding of the world of microorganisms and their impact on our lives. The program offered a rigorous and comprehensive curriculum that allowed me to explore the biology of bacteria, viruses, fungi, and other microorganisms, as well as their complex interactions with each other and their environment.
          One of the strong points of the program was gaining hands-on laboratory experience, where I had the opportunity to work with a diverse range of microorganisms and apply cutting-edge techniques to analyze their properties and behavior. Through research projects and collaborations with faculty members and fellow students, I developed critical thinking and problem-solving skills, which are essential in the field of microbiology. 
          
          Personally, I am most thankful to the program for introducing me to Bioinformatics, which I quickly identified as a field I would desire to pursue a career in. To that end, I did an internship in the [Computational Biology Group from the Institut of Biotecnologia and Biomedicina](https://ibb.uab.cat/wp-content/themes/viral/modules/ibb_membres/view_grup.php?CodiGrup=25) (IBB), where I took my first steps in Bioinformatics by familiarizing myself with Linux systems, command line interfaces and the development of Perl pipelines for sequence based identification of potential drug targets using the proteome of *Stenotrophomonas maltophilia*. 

  # - title: Potato # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #   - layout: top-middle
  #     title: Super awesome project
  #     link: github.com/sproogen
  #     # link_text: Project Website
  #     additional_links:
  #       - title:  sproogen/modern-resume-theme
  #         icon: fab fa-github
  #         url: github.com/sproogen/modern-resume-theme
  #     # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #     #   icon: fab fa-github
  #     #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #     quote: >
  #       This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #     description: | # this will include new lines to allow paragraphs
  #       I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Throughout my journey in the field of bioinformatics, I have gained experience in the following: 
        - <i class="fab fa-r-project"></i>   **R**
            - Executing and interpreting the results from popular differential expression packages such as *limma*, *DeSeq2* or *EdgeR*. 
            - Perform data management and cleaning through the usage of tidyverse packages such as *dplyr*, *readr* or *stringr*. 
            - Create data visualizations aimed at scientific reporting through *ggplot2*. 
            - Deploy in-house interactive apps for data visualization through *R Shiny*.   
        - <i class="fab fa-python"></i>   **Python**
            - 
        - <i class="fab fa-linux"></i>   **Linux/Bash**: 
        - <img src="images\Alecive-Flatwoken-Apps-Matlab.512.png" alt="MatlabIcon">  **Matlab**: 


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
